# Generated by Django 4.0.1 on 2022-01-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='contact_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='college',
            field=models.CharField(choices=[('CA', 'CA'), ('CBEA', 'CBEA'), ('CCJE', 'CCJE'), ('CHM', 'CHM'), ('CICS', 'CICS'), ('CTE', 'CTE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='college_year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='remarks',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('PENDING', 'PENDING'), ('OK', 'OK')], default='NEW', max_length=10),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='scholarship_program',
            field=models.CharField(choices=[('CHED-TDP', 'CHED-TDP'), ('CHED-TES', 'CHED-TES')], max_length=40),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
