# Generated by Django 4.0.1 on 2022-01-19 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0005_remove_scholar_user_alter_scholar_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholar',
            name='student_ID',
        ),
    ]
